/*
 ============================================================================
 Name        : Lab8.c
 Author      :
 Revised by  :
 Version     :
 Copyright   : Copyright 2020
 Description : Lab 8 in C, ANSI-C Style
 ============================================================================
 */

#include "header.h"
// Menu for the testing.
char *menu =    "\n" \
                " ***********Please select the following options**********************\n" \
                " *    This is the memory operation menu (Lab 8)            *\n" \
                " ********************************************************************\n" \
                " *    1. Write a double-word (32-bit) to the memory            *\n"  \
                " ********************************************************************\n" \
                " *    2. Read a byte (8-bit) data from the memory            *\n" \
                " *    3. Read a double-word (32-bit) data from the memory           *\n" \
                " ********************************************************************\n" \
                " *    4. Generate a memory dump from any memory location            *\n" \
                " ********************************************************************\n" \
                " *    e. To Exit, Type 'e'  or 'E'            *\n" \
                " ********************************************************************\n";

//---------------------------------------------------------------
// Generate a random number between 0x00 and 0xFF.
unsigned char rand_generator()
{
    return rand()%255;  // generate a random number between 0 and 255.
}
//---------------------------------------------------------------
void free_memory(char *base_address)
{
    free(base_address);  // free memory after use to avoid memory leakage.
    return;
}
//---------------------------------------------------------------
char *init_memory()
{
    char *mem = malloc(MEM_SIZE);  // allocate the memory
    // step 0: Start filling in the memory contents with
    //         random number generated by rand_generator() etc.

int i;
for(i=0; i< 255; i++)

   *(mem+i)=0;//rand_generator();

return mem;
}


//---------------------------------------------------------------
void write_dword(char *base_address, int offset, unsigned int dword_data){
    // Step 1: write a double-word to address: "base_address + offset".

sscanf(base_address+offset, "%08X",dword_data);

//printf("in write -%X",data);    
}
//---------------------------------------------------------------
unsigned char read_byte(char *base_address, int offset){
    // Step 2: return and print the byte from address: "base_address + offset".
 ssize_t bytess;
char info[256];
int f;
sprintf(info,"%X", *base_address+offset);

   bytess =strlen( info);   

   printf("%lu",bytess);

 return bytess;
}
//---------------------------------------------------------------
unsigned int read_dword(char *base_address, int offset){
    // Step 3: return and print the double-word from address: "base_address + offset".

unsigned int ret = (unsigned int) base_address+offset;  
return ret;


}
//---------------------------------------------------------------
void memory_dump(char *base_address, int offset, unsigned int dumpsize){
    // Step 4: Generate a memory dump display starting from address "base_address + offset".
    //        i.e., Display the contents of dump_size bytes starting from  "base_address + offset"
    //        dump_size should be a parameter.
    //        The memory dump display should be similar to the screenshot on the lab manual:
    if (dumpsize < MIN_DUMP_SIZE || dumpsize > MEM_SIZE)
        dumpsize = MIN_DUMP_SIZE; 


int i,a,b;

    for (i = 0; i<dumpsize ; i++ ){
printf("\n%X: ",base_address+offset + i);

     for (b=0; b<0x14; b++)
    //     if (*(base_address + i) < 0x7E && *(base_address + i) >= 0x20){
             printf("%02X ",(unsigned char)*(base_address+offset+b+i) );

     for(a = 0; a<0x14; a++){
        if (*(base_address + i+a) < 0x7E && *(base_address + i+a) >= 0x20)
        {
        printf(" %c ",(unsigned char)*(base_address+offset+i*a));           
        }else printf(".");
                 

         }
    }


    return;

}

//---------------------------------------------------------------
void setup_memory()
{
    // Now we need to setup the memory controller for the computer system we
    // will build. Basic requirements:
    // 1. Memory size needs to be 1M Bytes
    // 2. Memory is readable/writable with Byte and Double-Word Operations.
    // 3. Memory can be dumped and shown on screen.
    // 4. Memory needs to be freed (released) at the end of the code.
    // 6. For lab 8, we need to have a user interface to fill in memory,
    //                                      read memory and do memory dump.
    char *mem = init_memory();  // initialize the memory.
    char options =0;
    unsigned int offset, dumpsize;
    char byte_data;    // 8-bit operation.
    unsigned int dword_data;      // 32-bit operation.
    do{
        if (options != 0x0a)  // if options has a return key input, skipit.
        {
            puts(menu); /* prints Memory Simulation */
            printf ("\nThe base address of your memory is: %Xh (HEX)\n",(unsigned int) *mem);  // output base memory first.
            puts("Please make a selection:");  // output base memory first.
        }
            options = getchar();

            switch (options)
            {
                case '1':  // write double word.
                    puts("Please input your memory's offset address (in HEX):");
                    scanf("%x", (unsigned int*)&offset);    // input an offset address (in HEX) to write.
                    puts("Please input your DOUBLE WORD data to be written:");
                    scanf("%x", (unsigned int*)&dword_data);    // inputdata
                    write_dword (mem, offset, dword_data);  // write a double word to memory.
                    continue;
                case '2':  // read byte.
                    puts("Please input your memory's offset address (in HEX):");
                    scanf("%x", &offset);    // input an offset address (in HEX) to write.
                    read_byte(mem, offset);
                    continue;
                case '3':  // read double word.
                    puts("Please input your memory's offset address (in HEX):");
                    scanf("%x", &offset);    // input an offset address (in HEX) to write.
                    read_dword(mem, offset);
                    continue;
                case '4':  // generate memory dump starting at offset address (in HEX).
                    puts("Please input your memory's offset address (in HEX, should be a multiple of 0x10h):");
                    scanf("%x", &offset);    // input an offset address (in HEX) to start.
                    puts("Please input the size of the memory to be dumped (between 256 and 1M ):");
                    scanf("%d", &dumpsize);    // The size of the memorydump
                    memory_dump(mem, offset, dumpsize);  // generate a memory dump display of dumpsize bytes.
                    continue;
                case 'e':
                case 'E':
                    puts("Code finished, exit now");
                    free_memory(mem);
                    getchar();
                    return;  // return to main program.
                default:
                    // puts("Not a valid entry, please try again");
                    continue;
            }
    }while (1);  // make sure the only exit is from 'e'.
    return;
}
